### ISSUE TITLE
install with pyrevit extend command and structure of the github folder

### ISSUE THREAD

**Issue by jmcouffin** [aussieBIMguru/pyRoovit#2]
@aussieBIMguru please read my answer here. https://github.com/eirannejad/pyRevit/issues/1626#issuecomment-1256245826
you can fix it by changing the structure of the folder from pyRoovit/pyRoovit.extension/pyRoovit.tab/ to pyRoovit.tab/

**Comment by jmcouffin** [comment]
![image](https://user-images.githubusercontent.com/7872003/191994017-0d54c123-225b-4b6b-8141-7bc4a8e41b70.png)

**Comment by aussieBIMguru** [comment]
Done! Thanks for the guidance. Added a fair amount of new tools and libraries in there now also, more to come in future...
